spring:
  application:
    name: AccountsService
  profiles.active: dev

server:
  port: 8080
  error:
      include-message: always
      include-binding-errors: always
      include-stacktrace: on_param
      include-exception: false

accounts.openapi.dev-url: "http://localhost:9900"
accounts.openapi.prod-url: "http://localhost:9943/api/v1"

---
spring:
  sql.init.mode: always
  config.activate.on-profile: dev
  devtools.restart.enabled: true
  datasource:
    url: "jdbc:h2:mem:accountsdb"
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    defer-datasource-initialization: true
  h2:
    console.enabled: true
    console.path: /h2-ui

server:
  port: 9900

debug: true
logging:
  path: /var/logs/
  file: /var/logs/accouts.log
  level:
    root: INFO



---
spring:
  config.activate.on-profile: prod
  datasource:
    url: "jdbc:mysql://localhost/accounts_db"
    driverClassName: com.mysql.cj.jdbc.Driver
    username: account_user
    password: acc123
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      generate-ddl: true

server:
  servlet.contextPath: /api/v1
  port: 9943
  ssl:
    key-store: accountKey.p12
    key-store-password: password
    keyStoreType: PKCS12
    keyAlias: accountKey

logging:
  level:
    root: error
  path: /var/logs/
  file: /var/logs/prod.log